---
- hosts: build_servers
  become: true
  vars:
    tomcat_version: "10.1.18"
    tomcat_user: "tomcat"
    tomcat_group: "tomcat"
    tomcat_home: "/opt/tomcat/{{ tomcat_version }}"

  tasks:
    - name: Install OpenJDK 11
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes

    - name: Add Tomcat group
      group:
        name: "{{ tomcat_group }}"
        state: present

    - name: Add Tomcat user
      user:
        name: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        system: yes
        createhome: false

    - name: Download Tomcat 10.1.18
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        validate_certs: yes

    - name: Create Tomcat installation directory
      file:
        path: "{{ tomcat_home }}"
        state: directory
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"

    - name: Extract Tomcat archive
      unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ tomcat_home }}"
        remote_src: yes
        extra_opts: [--strip-components=1]
        creates: "{{ tomcat_home }}/bin/startup.sh"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"

    - name: Find all shell scripts in Tomcat bin directory
      find:
        paths: "{{ tomcat_home }}/bin"
        patterns: "*.sh"
      register: shell_scripts

    - name: Make shell scripts executable
      file:
        path: "{{ item.path }}"
        mode: 'u+x'
      loop: "{{ shell_scripts.files }}"
      become: yes

